export { default as Navbar } from './Navbar'
export { default as Sidebar } from './Sidebar'
export { default as AppMain } from './AppMain'
export { default as TagsView } from './TagsView/index.vue'
export { default as Settings } from './Settings/index.vue'
export { default as PersonDate } from './PersonDate/index.vue'
export { default as Footer } from './footer/index.vue'
